### ISSUE TITLE
Update Travis CI configuration

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#130]
I smashed together two of @hvr's versions of `.travis.yml` to make one that would probably work pretty well for `containers` too, aside from some minor changes to some dependencies and such: https://github.com/treeowl/boxes/blob/master/.travis.yml. You may or may not want to remove some versions.

**Comment by tibbe** [comment]
We already have one for containers. The one you linked won't work. See the comments in the existing config file.

**Comment by hvr** [comment]
@tibbe I think the only thing you'd want to do for container's `.travis.yml` is to have the build-matrix read something like

```yaml
env:
- GHCVER=7.0.4 CABALVER=1.16
- GHCVER=7.4.2 CABALVER=1.16
- GHCVER=7.6.3 CABALVER=1.16
- GHCVER=7.8.4 CABALVER=1.18
- GHCVER=7.10.1 CABALVER=1.22
- GHCVER=head CABALVER=head

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=head
```
